version: '3.8'

services:
  partners-db:
    env_file: .env
    image: postgres:12.17
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
