version: '3.8'

services:
  ktrek-backed-course-app:
    container_name: ktrek-backed-course-app
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      DB_HOST: postgreSQL
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - ktrek

  # ktrek-backed-course-redis:
  #   container_name: ktrek-backed-course-redis
  #   restart: always
  #   env_file: .env
  #   image: 'redis:7.2.1-alpine'
  #   ports:
  #     - '${REDIS_PORT}:6379'

networks:
  ktrek:
    external: true
