version: '3.8'

services:
  # db:
  #   container_name: KTrek-backed-course-db
  #   env_file: .env
  #   restart: always
  #   image: postgres:12.17
  #   environment:
  #     POSTGRES_HOST: ${DB_HOST}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - ${DB_PORT}:5432
  #   volumes:
  #     - /private/var/lib/postgresql:/var/lib/postgresql

  redis:
    container_name: KTrek-backed-course-redis
    env_file: .env
    restart: always
    image: redis:6.2.2
    ports:
      - "6380:6379"

  app:
    container_name: KTrek-backed-course-app
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
    ports:
      - "${PORT_APP}:${PORT_APP}"
    depends_on:
      - redis
      # - db
